[platformio]
default_envs = esp32c3
src_dir = .
include_dir = ../Common

[env:esp32c3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

lib_deps =
    jgromes/RadioLib @ ^7.1.2
    mikalhart/TinyGPSPlus @ ^1.0.3
    bblanchon/ArduinoJson @ ^7.3.0

build_flags =
    -I ../Common
    -D CORE_DEBUG_LEVEL=0
